import { useParams } from "react-router-dom";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

const CAMPAIGN = {
  name: "Q2 Outbound — Enterprise SaaS",
  status: "Active",
  period: "April 2026",
};

const STATS = [
  { label: "Emails Sent", value: "1,247" },
  { label: "Open Rate", value: "34.2%" },
  { label: "Reply Rate", value: "8.7%" },
  { label: "Meetings Booked", value: "12" },
];

const ACTIVITY = [
  { date: "Apr 8", contact: "Sarah Chen", company: "Acme Corp", status: "Replied" },
  { date: "Apr 7", contact: "Marcus Rivera", company: "TechFlow", status: "Opened" },
  { date: "Apr 6", contact: "Emma Patel", company: "DataSync", status: "Sent" },
  { date: "Apr 5", contact: "James Liu", company: "ScaleUp", status: "Replied" },
  { date: "Apr 4", contact: "Ana Costa", company: "FlowTech", status: "Bounced" },
];

const statusVariant: Record<string, "default" | "secondary" | "destructive" | "outline"> = {
  Replied: "default",
  Opened: "secondary",
  Sent: "outline",
  Bounced: "destructive",
};

const ClientPortal = () => {
  const { token } = useParams<{ token: string }>();

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b bg-card">
        <div className="max-w-5xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-lg bg-primary/10 flex items-center justify-center text-primary font-bold text-sm">
              A
            </div>
            <span className="text-base font-semibold text-foreground">[Agency Name]</span>
          </div>
          <span className="text-xs text-muted-foreground">Powered by SalesOS</span>
        </div>
      </header>

      {/* Main content */}
      <main className="max-w-5xl mx-auto px-6 py-10 space-y-8">

        {/* Campaign overview */}
        <Card className="p-6">
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
            <div>
              <p className="text-xs text-muted-foreground uppercase tracking-wide mb-1">Campaign</p>
              <h1 className="text-2xl font-bold">{CAMPAIGN.name}</h1>
              <p className="text-sm text-muted-foreground mt-1">{CAMPAIGN.period}</p>
            </div>
            <Badge className="self-start sm:self-center bg-green-500/10 text-green-600 border-green-500/20 hover:bg-green-500/20">
              {CAMPAIGN.status}
            </Badge>
          </div>
        </Card>

        {/* Stats grid */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
          {STATS.map((stat) => (
            <Card key={stat.label} className="p-5 text-center">
              <p className="text-3xl font-bold">{stat.value}</p>
              <p className="text-sm text-muted-foreground mt-1">{stat.label}</p>
            </Card>
          ))}
        </div>

        {/* Recent activity table */}
        <Card className="p-6">
          <h2 className="text-lg font-semibold mb-4">Recent Activity</h2>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Date</TableHead>
                <TableHead>Contact</TableHead>
                <TableHead>Company</TableHead>
                <TableHead>Status</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {ACTIVITY.map((row, i) => (
                <TableRow key={i}>
                  <TableCell className="text-muted-foreground">{row.date}</TableCell>
                  <TableCell className="font-medium">{row.contact}</TableCell>
                  <TableCell>{row.company}</TableCell>
                  <TableCell>
                    <Badge variant={statusVariant[row.status] ?? "outline"}>
                      {row.status}
                    </Badge>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </Card>
      </main>

      {/* Footer */}
      <footer className="border-t mt-12">
        <div className="max-w-5xl mx-auto px-6 py-4 text-center">
          <p className="text-xs text-muted-foreground">
            Report generated by SalesOS &bull; salesos.alephwavex.io
          </p>
        </div>
      </footer>
    </div>
  );
};

export default ClientPortal;
