ALTER TABLE public.icp_profiles
  ADD COLUMN IF NOT EXISTS departments jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS seniority_levels jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS business_model text,
  ADD COLUMN IF NOT EXISTS funding_stages jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS growth_stage text,
  ADD COLUMN IF NOT EXISTS event_triggers jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS intent_keywords jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS competitor_tools jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS exclude_industries jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS exclude_titles jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS exclude_keywords jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS value_proposition text,
  ADD COLUMN IF NOT EXISTS use_cases jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS objections jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS success_metrics jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS preferred_channels jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS customer_examples text,
  ADD COLUMN IF NOT EXISTS deal_size_range text,
  ADD COLUMN IF NOT EXISTS sales_cycle text,
  ADD COLUMN IF NOT EXISTS budget_authority text,
  ADD COLUMN IF NOT EXISTS company_age_range text,
  ADD COLUMN IF NOT EXISTS hiring_signals jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS scoring_weights jsonb DEFAULT '{"title":25,"industry":25,"size":25,"tech":25}'::jsonb;